sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js: '8'
install: npm install
script:
  - npm run lint
  - npm run build
after_success: npm run semantic-release